### ISSUE TITLE
这破解版的有毒

### ISSUE THREAD

**Issue by idreamsoft** [champion32/WeAppIdeIssue#2]
MD 刚才下了这个破解版的微信小程序IDE 
然后没一会就被拉到一个群叫微信小程序开发推广 
难道这破解版的有毒

**Comment by champion32** [comment]
非常抱歉,没有详细验证过.
这是最早的时候在github上拿到的地址下载的.readme中有提及

另外抱歉回复信息有些慢.

另外,11月3日,微信开放公测了.
